name: 'Upstream tracker'
on:
  schedule:
    - cron:  '12 17 * * *'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  track_upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Set up git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get upstream
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git remote add -f upstream https://github.com/mickael-kerjean/filestash.git

      - name: Get master build status
        run:  |
          upstream_master=$(git rev-parse upstream/master)
          upstream_status=$(gh api -H "Accept: application/vnd.github+json" /repos/mickael-kerjean/filestash/commits/${upstream_master}/status | jq -r .state)
          echo upstream_status=${upstream_status} >> $GITHUB_ENV
          echo "${upstream_master} build status is ${upstream_status}"

      - name: Check for changes
        run:  |
          upstream_changes=$(git log --format=%H HEAD..upstream/master)
          echo upstream_changes=${upstream_changes} >> $GITHUB_ENV
          echo "upstream changes ${upstream_changes}"

      - name: Merge upstream
        if: ${{ env.upstream_status == 'success' && env.upstream_changes != '' }}
        run: |
          upstream_master=$(git rev-parse upstream/master)
          branch_name=upstream-merge-$(date -u +%Y%m%d%H%M)
          git checkout -b ${branch_name} origin/master
          git merge -m "Automatic upstream merge (${upstream_master})" upstream/master
          git show
          git push origin --set-upstream ${branch_name}
          gh pr create --repo fredriklindberg/filestash --base master --title "Automatic merge of upstream $(date -u +%Y%m%d)" --body "Automatic upstream merge" -a fredriklindberg

